### ISSUE TITLE
SplitStr.coffee use default value at first run 

### ISSUE THREAD

**Issue by code-rider** [noflo/noflo-strings#14]
i am facing a problem with similar components of SplitStr.coffee
i use this component in browser.
inport receive data packets from other component and for delimiter i set space characters. so i type space in delimiter in browser.
but when i run graph SplitStr.coffee use "\n" default value at first run.
but when i rerun without refresh this component use space for delimiter. when i refresh page and run it use default one again.

how to fix
thanks

**Comment by bergie** [comment]
Given that the port has a default value, you should ensure your custom delimiter is sent before values. Easiest is to do that by proving it as an Initial Information Packet in your graph.
