### ISSUE TITLE
Tests broken with NoFlo > 0.5.9

### ISSUE THREAD

**Issue by jonnor** [noflo/noflo-strings#15]
The `noflo-test` based tests are currently failing: https://travis-ci.org/noflo/noflo-strings/builds/69503391
With NoFlo 0.5.9 it however works https://travis-ci.org/noflo/noflo-strings/builds/36458976

This seems to be due to noflo-test not being compatible with newer. Possibly due to noflo/noflo-test#12
That is now fixed, however the library broke API when moving to Mocha. `discuss` is now `describe` and one must additionally use `it`. Neccesitating rewriting the tests in noflo-string to match (and releaseing a new noflo-test)

**Comment by bergie** [comment]
I'm removing noflo-test from here altogether
